### ISSUE TITLE
Live watch mode

### ISSUE THREAD

**Issue by Mario8419** [colbyfayock/gatsby-starter-leaflet#170]
thank you for the starter, great! But can you plz tell me where to put watch: true to get live updates for the map, marker?

**Comment by colbyfayock** [comment]
hey im not familiar with this one! can you link me to what you're referring to?

**Comment by Mario8419** [comment]
https://leafletjs.com/reference-1.7.1.html#locate-options

**Comment by colbyfayock** [comment]
this is the function that's currently grabbing the geolocation in this starter which is using the native browser method not the Leaflet geolocator

https://github.com/colbyfayock/gatsby-starter-leaflet/blob/248a809852ae596255bc0db5a394c0b7d4c33b07/src/lib/map.js#L36

you'd want to swap that for the Leaflet version so that you can pass in that option
